### PR TITLE
Add Albanian

### PR DESCRIPTION
**Pull request by cocka11**
# WE DO NOT MERGE PULL REQUESTS SUBMITTED HERE

You will need to submit it through [OmniRom Gerrit](https://gerrit.omnirom.org/#/admin/projects/android_bootable_recovery/)

For changes to device trees, use [TWRP Gerrit](https://gerrit.twrp.me/)

This guide explani how to use [Gerrit code review](https://forum.xda-developers.com/general/xda-university/guide-using-gerrit-code-review-t3720802)

### CODE REVIEW

**Comment by bigbiff** [comment]
We do not accept Pull Requests here. Please use https://gerrit.twrp.me for adding this patchset.

**Comment by cocka11** [comment]
how to use this. any help

**Review by ratchanonsuttawas — APPROVED** [review]
83da9a0e3825ed94e0f83d236da71c343661d59d

**Review by ratchanonsuttawas — COMMENTED** [review]
83da9a0e3825ed94e0f83d236da71c343661d59d

**Comment by ratchanonsuttawas** [comment]
83da9a0e3825ed94e0f83d236da71c343661d59d

**Comment by ratchanonsuttawas** [comment]
> # WE DO NOT MERGE PULL REQUESTS SUBMITTED HERE
> 
> You will need to submit it through [OmniRom Gerrit](https://gerrit.omnirom.org/#/admin/projects/android_bootable_recovery/)
> 
> For changes to device trees, use [TWRP Gerrit](https://gerrit.twrp.me/)
> 
> This guide explani how to use [Gerrit code review](https://forum.xda-developers.com/general/xda-university/guide-using-gerrit-code-review-t3720802)

**Comment by ratchanonsuttawas** [comment]
> 83da9a0e3825ed94e0f83d236da71c343661d59d

**Comment by ratchanonsuttawas** [comment]
> # WE DO NOT MERGE PULL REQUESTS SUBMITTED HERE
> 
> You will need to submit it through [OmniRom Gerrit](https://gerrit.omnirom.org/#/admin/projects/android_bootable_recovery/)
> 
> For changes to device trees, use [TWRP Gerrit](https://gerrit.twrp.me/)
> 
> This guide explani how to use [Gerrit code review](https://forum.xda-developers.com/general/xda-university/guide-using-gerrit-code-review-t3720802)

**Comment by ratchanonsuttawas** [comment]
gui/theme/common/languages/sq.xml

**Comment by ratchanonsuttawas** [comment]
e075a0313af13c39d1db1e4405b67a1e8d667df4

**Comment by ratchanonsuttawas** [comment]
83da9a0e3825ed94e0f83d236da71c343661d59d

**Pull request closed without merging**
